# Generated by Django 5.2.17 on 2026-08-18 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('website', '企业官网'), ('wechat', '官方招聘公众号')], max_length=16)),
                ('source_url', models.URLField()),
                ('admission_evidence', models.TextField()),
                ('access_policy', models.CharField(default='低频、公开、无需登录访问', max_length=300)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('adapter_name', models.CharField(default='html_selector', max_length=64)),
                ('parser_config', models.JSONField(blank=True, default=dict)),
                ('last_etag', models.CharField(blank=True, max_length=255)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', '计划任务'), ('manual', '手动更新')], max_length=16)),
                ('scheduled_for_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('partial_failure', '部分失败'), ('failed', '失败')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', '成功'), ('not_modified', '未变化'), ('failed', '失败')], max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fetch_runs', to='radar.officialsource')),
                ('update_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fetch_runs', to='radar.updaterun')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('company_type', models.CharField(choices=[('internet', '互联网/科技'), ('state_owned', '央企/国企'), ('other', '其他')], max_length=24)),
                ('industry', models.CharField(max_length=100)),
                ('official_domain', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='radar.organization')),
            ],
        ),
        migrations.AddField(
            model_name='officialsource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_sources', to='radar.organization'),
        ),
        migrations.CreateModel(
            name='RecruitmentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('official_notice_url', models.URLField()),
                ('recruitment_type', models.CharField(default='校园招聘', max_length=64)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '招聘中'), ('expired', '已截止'), ('withdrawn', '已撤回')], default='active', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_notices', to='radar.organization')),
            ],
        ),
        migrations.CreateModel(
            name='NoticePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location_text', models.CharField(max_length=300)),
                ('normalized_locations', models.JSONField(blank=True, default=list)),
                ('raw_text', models.TextField(blank=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='radar.recruitmentnotice')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_applied', '未投递'), ('applied', '已投递'), ('written_test', '已笔试'), ('interviewed', '已面试'), ('rejected', '已挂'), ('passed_interview', '面试通过'), ('not_applying', '暂不投递')], default='not_applied', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='application_progress', to='radar.recruitmentnotice')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('link_type', models.CharField(choices=[('notice', '公告页'), ('application', '投递入口')], max_length=16)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_links', to='radar.noticeposition')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_links', to='radar.recruitmentnotice')),
            ],
        ),
        migrations.CreateModel(
            name='SourceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField()),
                ('content_hash', models.CharField(max_length=64)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetch_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_version', to='radar.fetchrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='radar.officialsource')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64)),
                ('excerpt', models.TextField()),
                ('locator', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='radar.recruitmentnotice')),
                ('source_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='radar.sourceversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recruitmentnotice',
            constraint=models.UniqueConstraint(fields=('organization', 'official_notice_url'), name='unique_notice_per_organization_and_url'),
        ),
    ]
