# Generated by Django 5.2.17 on 2026-08-18 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recruitmentnotice',
            name='unique_notice_per_organization_and_url',
        ),
        migrations.AddField(
            model_name='applicationlink',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationlink',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='application_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='radar.applicationlink'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='radar.noticeposition'),
        ),
        migrations.AddField(
            model_name='noticeposition',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noticeposition',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='allowed_link_hosts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='officialsource',
            name='official_entrypoint_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitmentnotice',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_notices', to='radar.officialsource'),
        ),
        migrations.AlterField(
            model_name='officialsource',
            name='source_type',
            field=models.CharField(choices=[('website', '企业官网'), ('ats', '官网关联投递系统'), ('wechat', '官方招聘公众号')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='recruitmentnotice',
            constraint=models.UniqueConstraint(fields=('source', 'official_notice_url'), name='unique_notice_per_source_and_url'),
        ),
    ]
