# Generated by Django 5.2.17 on 2026-08-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_remove_recruitmentnotice_unique_notice_per_organization_and_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchrun',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('unchanged', '内容未变化'), ('not_modified', '未变化'), ('failed', '失败')], max_length=16),
        ),
    ]
