# Generated by Django 5.2.17 on 2026-08-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0009_phase01r2_audit_chain_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsource',
            name='source_type',
            field=models.CharField(choices=[('website', '企业官网'), ('ats', '官网关联投递系统'), ('wechat', '官方招聘公众号'), ('api', '官方招聘接口')], max_length=16),
        ),
    ]
