# Generated by Django 5.2.17 on 2026-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0012_progress_per_recruitment_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_type',
            field=models.CharField(choices=[('private', '民企'), ('state_owned', '央国企'), ('foreign', '外资'), ('joint_venture', '中外合资'), ('bank', '银行'), ('public_institution', '事业单位'), ('social_organization', '社会机构')], max_length=24),
        ),
    ]
