# Generated by Django 5.2.17 on 2026-08-30 04:11

import hashlib
import json

import django.db.models.deletion
from django.db import migrations, models


SUPERSEDED_BATCHES = (
    ("美团", "phase-02:p08"),
    ("京东", "phase-02:p07"),
    ("腾讯", "phase-02:p01"),
    ("大疆创新", "phase-02:p14"),
)


def classify_superseded_batches_and_backfill_gate_event(apps, schema_editor):
    RecruitmentBatch = apps.get_model("radar", "RecruitmentBatch")
    RecruitmentPolicy = apps.get_model("radar", "RecruitmentPolicy")
    RecruitmentPolicyEvent = apps.get_model("radar", "RecruitmentPolicyEvent")
    for company, identity_key in SUPERSEDED_BATCHES:
        RecruitmentBatch.objects.filter(
            organization__name=company,
            identity_key=identity_key,
            announcement_admission="pending",
        ).update(announcement_admission="superseded")
    policy = RecruitmentPolicy.objects.filter(
        key="default", announcement_gate_enforced=True
    ).first()
    if (
        policy is None
        or len(policy.preview_digest) != 64
        or RecruitmentPolicyEvent.objects.filter(policy=policy).exists()
    ):
        return
    previous_hash = "0" * 64
    actor = "migration-0024"
    payload = json.dumps(
        {
            "policy_id": policy.pk,
            "event_type": "activated",
            "actor_label": actor,
            "preview_digest": policy.preview_digest,
            "previous_event_hash": previous_hash,
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    )
    RecruitmentPolicyEvent.objects.create(
        policy=policy,
        event_type="activated",
        actor_label=actor,
        preview_digest=policy.preview_digest,
        previous_event_hash=previous_hash,
        event_hash=hashlib.sha256(payload.encode("utf-8")).hexdigest(),
    )


def reverse_superseded_batches_and_gate_event(apps, schema_editor):
    RecruitmentBatch = apps.get_model("radar", "RecruitmentBatch")
    RecruitmentPolicyEvent = apps.get_model("radar", "RecruitmentPolicyEvent")
    for company, identity_key in SUPERSEDED_BATCHES:
        RecruitmentBatch.objects.filter(
            organization__name=company,
            identity_key=identity_key,
            announcement_admission="superseded",
        ).update(announcement_admission="pending")
    RecruitmentPolicyEvent.objects.filter(actor_label="migration-0024").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0023_allow_shared_portal_across_batches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentbatch',
            name='announcement_admission',
            field=models.CharField(choices=[('legacy', '旧规则待迁移'), ('admitted', '公告已准入'), ('pending', '待核验'), ('superseded', '已被精确批次取代'), ('excluded', '不进入正式页')], default='legacy', max_length=16),
        ),
        migrations.CreateModel(
            name='RecruitmentPolicyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('activated', '公告门控已开启')], max_length=24)),
                ('actor_label', models.CharField(max_length=100)),
                ('preview_digest', models.CharField(max_length=64)),
                ('previous_event_hash', models.CharField(max_length=64)),
                ('event_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='radar.recruitmentpolicy')),
            ],
        ),
        migrations.RunPython(
            classify_superseded_batches_and_backfill_gate_event,
            reverse_superseded_batches_and_gate_event,
        ),
    ]
