# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0024_superseded_batches_and_policy_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentbatch",
            name="recruitment_type",
            field=models.CharField(
                choices=[
                    ("spring", "春招"),
                    ("spring_supplement", "春招补录"),
                    ("summer", "夏招"),
                    ("autumn", "秋招"),
                    ("autumn_supplement", "秋招补录"),
                    ("autumn_early", "秋招提前批"),
                    ("campus_recruitment", "校园招聘"),
                    ("internship", "实习"),
                    ("special_program", "专项计划"),
                    ("other", "其他"),
                    ("unknown", "未知"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
