# Generated by Django 5.2.17 on 2026-09-02 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def populate_candidate_identity_urls(apps, schema_editor):
    Candidate = apps.get_model("radar", "AnnouncementDiscoveryCandidate")
    for candidate in Candidate.objects.only("pk", "url").iterator():
        Candidate.objects.filter(pk=candidate.pk).update(identity_url=candidate.url)


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0034_rename_wxcli_verification_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementDiscoveryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent_key', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=500)),
                ('provider', models.CharField(max_length=64)),
                ('request_key', models.CharField(max_length=64)),
                ('rank', models.PositiveSmallIntegerField()),
                ('result_id', models.CharField(max_length=128)),
                ('title_hint', models.CharField(blank=True, max_length=500)),
                ('backend_date_hint', models.CharField(blank=True, max_length=64)),
                ('snippet_sha256', models.CharField(blank=True, max_length=64)),
                ('company_signal_found', models.BooleanField(default=False)),
                ('recruitment_signal_found', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementDiscoveryOrganizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', '完成'), ('degraded', '降级完成'), ('failed', '失败')], max_length=16)),
                ('fallback_reason', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementDiscoveryProviderAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('request_key', models.CharField(max_length=64)),
                ('intent_key', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('success', '成功'), ('empty', '空结果'), ('transient_error', '瞬时错误'), ('permanent_error', '永久错误'), ('skipped', '跳过')], max_length=24)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('result_count', models.PositiveSmallIntegerField(default=0)),
                ('cost_dollars', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementDiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('complete', '完成'), ('partial', '部分完成'), ('failed', '失败')], max_length=16)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('error_code', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='announcementdiscoverycandidate',
            name='identity_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='announcementdiscoverycandidate',
            name='route_state',
            field=models.CharField(choices=[('unrouted', '尚未分流'), ('known_official', '已知官网'), ('known_ats', '已知招聘系统'), ('source_identity_review_required', '来源身份待审查'), ('rejected', '已拒绝')], default='unrouted', max_length=40),
        ),
        migrations.RunPython(populate_candidate_identity_urls, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='announcementdiscoverycandidate',
            constraint=models.UniqueConstraint(fields=('organization', 'identity_url'), name='unique_announcement_candidate_identity_per_org'),
        ),
        migrations.AddField(
            model_name='announcementdiscoveryobservation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_observations', to='radar.announcementdiscoverycandidate'),
        ),
        migrations.AddField(
            model_name='announcementdiscoveryorganizationrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcement_discovery_runs', to='radar.organization'),
        ),
        migrations.AddField(
            model_name='announcementdiscoveryobservation',
            name='organization_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='radar.announcementdiscoveryorganizationrun'),
        ),
        migrations.AddField(
            model_name='announcementdiscoveryproviderattempt',
            name='organization_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_attempts', to='radar.announcementdiscoveryorganizationrun'),
        ),
        migrations.AddField(
            model_name='announcementdiscoveryorganizationrun',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_runs', to='radar.announcementdiscoveryrun'),
        ),
        migrations.AddConstraint(
            model_name='announcementdiscoveryobservation',
            constraint=models.UniqueConstraint(fields=('organization_run', 'candidate', 'provider', 'request_key', 'result_id'), name='unique_discovery_observation_per_run'),
        ),
        migrations.AddConstraint(
            model_name='announcementdiscoveryproviderattempt',
            constraint=models.UniqueConstraint(fields=('organization_run', 'provider', 'request_key'), name='unique_provider_attempt_per_discovery_query'),
        ),
        migrations.AddConstraint(
            model_name='announcementdiscoveryorganizationrun',
            constraint=models.UniqueConstraint(fields=('run', 'organization'), name='unique_organization_per_discovery_run'),
        ),
    ]
